kind: Service
apiVersion: v1
metadata:
  name: cool-statefulapp-service
spec:
  selector:
    app: stateful-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP
